version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  hrml_parser:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8000:8000"
    image: html_parser_api